downloadVideo/urls.py
from django.urls import path
from . import views

app_name = 'downloadVideo'

urlpatterns = [
    path('', views.home, name='home'),
    path('download-video/', views.download_video, name='download'),

]

socialMedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('downloadVideo.urls'))
]

downloadVideo/models.py
from django.db import models


class Download(models.Model):
    url = models.URLField()

    def __str__(self):
        return self.url

downloadVideo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from django.views.generic import TemplateView
import youtube_dl
from django.contrib import messages


def home(request):
    return render(request, 'index.html')


def download_video(request):
    if request.method == 'POST':
        video_url = request.POST['url']
        if video_url:
            ydl_opts = {'outtmp1': 'D:/'}
            with youtube_dl.YoutubeDL(ydl_opts) as ydl:
                ydl.download([video_url])
            messages.success(request, 'Video Downloaded.')
            return redirect('downloadVideo:home')
        else:
            messages.warning(request, 'Please Enter Video URL')
            return redirect('downloadVideo:home')
    return redirect('downloadVideo:home')

downloadVideo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} {% endblock %} </title>
</head>
<body>
    
    {% block body %}

    {% endblock %}
    
</body>
</html>

downloadVideo/templates/index.html
{% extends 'base.html' %}
{% block title %}
    Home | Download Video
{% endblock %}

{% block body %}


<div class="container" style="position: absolute; left: 100px;">
    <div class="container my-4" style="border:1px solid; background: black;">
        <h1>YouTube Video Downloader</h1>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    <div class="container">
        <div class="mb-3">
            <form action="{% url 'downloadVideo:download' %}" method="post">
                {% csrf_token %}
                <label for="exampleFormControlInput1" class="form-label"><b>Enter Video URL</b></label>
                <input type="text" class="form-control" name="url" id="url_name" placeholder="YouTube video URL">
                <br><br>
                <button type="submit" class="form-control btn btn-danger" id="btn">Download</button>
            </form>
        </div>

    </div>
    <div class="container w-25">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">Start Downloading</button>
        </div>
        {% endfor %}
        {% endif %}
        <p id="para_alert"></p>
    </div>
</div>

{% endblock %}

    